# Generated by Django 4.0.4 on 2022-05-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='artical_type',
            field=models.IntegerField(choices=[(0, 'Travel_Dev'), (1, 'Game_Dev'), (2, 'Web_Dev')], default=0),
        ),
    ]
