# Generated by Django 4.0.4 on 2022-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0002_blogpost_artical_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='artical_type',
            field=models.IntegerField(choices=[(0, 'Travel Dev'), (1, 'Game Dev'), (2, 'Web Dev')], default=0),
        ),
    ]
